version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: "1.24.5"
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true
      print-linter-name: true

linters_settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  misspell:
    locale: US
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: var-naming

linters:
  enable:
    - bodyclose
    - depguard
    - dupl
    - errcheck
    - gocyclo
    - ineffassign
    - lll
    - misspell
    - nakedret
    - unused
    - revive

issues:
  exclude_rules:
    - path: "_test\\.go"
      linters:
        - mnd
      text: "Magic number"
    - path: "internal/bot/handlers\\.go"
      linters:
        - errcheck
      text: "Error return value of `b\\.SendMessage` is not checked"
    - path: "internal/bot/handlers\\.go"
      linters:
        - errcheck
      text: "Error return value of `b\\.AnswerCallbackQuery` is not checked"