version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: "1.22"

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - gofmt
    - goimports

output:
  sort-results: false  # This was removed as unsupported
  format: "json"       # Adjusted to meet schema

run-settings:
  exclude:
    - _test\.go        # Adjust path exclusion
    - internal/bot     # Broad exclusion adjusted

tests:
  test-timeout: 3m
