version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: "1.22"

linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

output:
  format: line-color
  color: auto

issues:
  exclude-use-default: false
  exclude:
    - path: _test\.go
      text: "Magic number"
    - path: internal/bot/handlers\.go
      text: "Error return value of"

