version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: "1.24.5"
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true
      print-linter-name: true

linters:
  settings:
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: var-naming
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/AndrePim/telegram_english_learn_bot
            - github.com/go-telegram/bot
            - github.com/joho/godotenv
            - github.com/lib/pq
  enable:
    - bodyclose
    - depguard
    - dupl
    - errcheck
    - gocyclo
    - ineffassign
    - lll
    - misspell
    - nakedret
    - unused
    - revive
  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - mnd
        text: "Magic number"
      - path: "internal/bot/handlers\\.go"
        linters:
          - errcheck
        text: "Error return value of `b\\.EditMessageText` is not checked"
      - path: "cmd/app/main\\.go"
        linters:
          - errcheck
        text: "Error return value of `db\\.Close` is not checked"
      - path: "internal/repository/word_repository\\.go"
        linters:
          - errcheck
        text: "Error return value of `rows\\.Close` is not checked"
      - path: "internal/service/image_service\\.go"
        linters:
          - errcheck
        text: "Error return value of `resp\\.Body\\.Close` is not checked"

formatters:
  enable:
    - gofmt
    - goimports