version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: "1.24.5"

linters:
  disable-all: false
  enable:
    - bodyclose
    - depguard
    - dupl
    - errcheck
    - gocyclo
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - unused

output:
  print-linter-name: true

issues:
  exclude:
    - path: _test\.go
      text: "Magic number"
    - path: internal/bot/handlers\.go
      text: "Error return value"

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  misspell:
    locale: US
