version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  # Убедись, что версия Go соответствует реальной версии в CI (например, '1.22')
  go: "1.22"

# Включаем форматтеры кода (не путать с форматом вывода)
formatters:
  enable:
    - gofmt
    - goimports

# Настройки линтеров и форматтеров
linters-settings:
  goimports:
    local-prefixes:
      - github.com/AndrePim/telegram_english_learn_bot
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags: [diagnostic, experimental, opinionated, performance, style]
    disabled-checks: [dupImport, ifElseChain, octalLiteral, whyNoLint, wrapperFunc]
  # golint устарел — лучше убрать или перейти на revive/stylecheck
  # golint:
  #   min-confidence: 0

# Формат вывода сообщений линтера
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    # - golint        # устарел — лучше отключить
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters: [gomnd]
    - path: internal/bot/handlers.go
      linters: [errcheck]
      text: "Error return value of `b.SendMessage` is not checked"
    - path: internal/bot/handlers.go
      linters: [errcheck]
      text: "Error return value of `b.AnswerCallbackQuery` is not checked"
