version: "2" # Версия конфигурации v2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: '1.24.5'
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true
      print-linter-name: true

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: ["github.com/AndrePim/telegram_english_learn_bot"]
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: var-naming

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - mnd
    - revive
  exclude:
    - 'Error return value of `b\.SendMessage` is not checked'
    - 'Error return value of `b\.AnswerCallbackQuery` is not checked'
  exclude-dirs:
    - _test\.go

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
    - path: internal/bot/handlers.go
      linters:
        - errcheck
      text: "Error return value of `b.SendMessage` is not checked"
    - path: internal/bot/handlers.go
      linters:
        - errcheck
      text: "Error return value of `b.AnswerCallbackQuery` is not checked"